services:
  outout-api:
    build:
      context: .               # current folder has everything (Dockerfile + .sln + projects)
      dockerfile: Dockerfile
    container_name: outout-api
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - mongo
    networks:
      - outout-net

  mongo:
    image: mongo:6.0
    container_name: outout-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - outout-net

networks:
  outout-net:
    driver: bridge

volumes:
  mongo_data:
